version: '2.26'

services:
  db:
    image: postgres:15.4-alpine
    container_name: banner_db
    restart: always
    env_file:
      - ../.env
    ports:
      - '5431:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: